math operations
parth262/java-dataframe pull request #2
Opened 2024-02-26 11:59 UTC by arpanshah19

2024-02-26 13:31 UTC, parth262 requested changes

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/Divide.java
> +        return String.valueOf(firstValue.doubleValue() / secondValue.doubleValue());
Do not cast it to string. Let's return whatever the result is as is

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/NumberArrayTransformation.java
> +            return null;
throw the runtime error instead of returning null

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/Power.java
> +        return String.valueOf(Math.pow(firstValue.doubleValue(), secondValue.doubleValue()));
Return the value without converting in string

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/Multiple.java
> +            return String.valueOf(firstValue.floatValue() * secondValue.floatValue());
Return value without converting in string

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/Subtract.java
> +            return String.valueOf(firstValue.floatValue() - secondValue.floatValue());
Return value without converting into String

2024-02-26 13:31 UTC, parth262 commented on lib/src/main/java/dataframe/transformation/number/Sum.java
> +            return String.valueOf(firstValue.floatValue() + secondValue.floatValue());
Return value without converting into String

2024-02-27 04:23 UTC, arpanshah19 commented on lib/src/main/java/dataframe/transformation/number/Divide.java
> +        return String.valueOf(firstValue.doubleValue() / secondValue.doubleValue());
Done

2024-02-27 04:23 UTC, arpanshah19 commented on lib/src/main/java/dataframe/transformation/number/NumberArrayTransformation.java
> +            return null;
Done

2024-02-27 04:23 UTC, arpanshah19 commented on lib/src/main/java/dataframe/transformation/number/Power.java
> +        return String.valueOf(Math.pow(firstValue.doubleValue(), secondValue.doubleValue()));
Done

2024-02-27 04:23 UTC, arpanshah19 commented on lib/src/main/java/dataframe/transformation/number/Subtract.java
> +            return String.valueOf(firstValue.floatValue() - secondValue.floatValue());
Done

2024-02-27 04:24 UTC, arpanshah19 commented on lib/src/main/java/dataframe/transformation/number/Sum.java
> +            return String.valueOf(firstValue.floatValue() + secondValue.floatValue());
Done

2024-02-28 08:14 UTC, parth262 approved these changes

2024-02-28 08:17 UTC, merged